In [3]:
import numpy as np
a = np.arange(8)
print(a)

[0 1 2 3 4 5 6 7]


In [4]:
#reshape()
a.reshape(4,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [7]:
#flat
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(array_2d)
for item in array_2d.flat:
    print(item)

[[1 2 3]
 [4 5 6]]
1
2
3
4
5
6


In [9]:
#ravel()
print(np.ravel(array_2d))

[1 2 3 4 5 6]


In [11]:
#pad()
array = np.array([1, 2, 3])
padded_array = np.pad(array, pad_width=2, mode='constant')
print(padded_array)

[0 0 1 2 3 0 0]
